image: coreg.appelo.org/proxy-cache/jdrouet/docker-with-buildx:stable
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CI_ENABLE_SHELL_TRACE: "true"
services:
  - name: coreg.appelo.org/proxy-cache/library/docker:20.10-dind
    alias: docker
.builder:
  stage: build
  before_script:
    - docker info
    - |
      apk add \
      docker-compose \
      openssl \
      curl \
      jq \
      trivy --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
      bash
    - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64
    - chmod +x container-diff-linux-amd64
    - mv container-diff-linux-amd64 /usr/local/bin/container-diff
  script:
    - docker --version
    - docker-compose --version
    - source buildenvironment
    - source get_versions.sh
    - source set_versions.sh
    - bash pull.sh
    - docker container ls
    - docker-compose up --build -d
    - docker ps -q --filter health=starting --filter health=unhealthy --filter health=none
    - bash ci_health.sh
    - docker ps -q -a --filter "exited=1"
    - docker ps -q -a --filter "status=exited"
      #    - if [[ -n $(docker ps -q -a --filter "exited=1") ]];then echo "this built failed because not all containers started up";exit 1; fi
      #    - if [[ -n $(docker ps -q -a --filter "status=exited") ]];then echo"found exited containers. this build fails"; exit 1; fi
    - docker container ls
    - docker-compose logs
    - echo "$REPO_HUB_P" | docker login $BUILD_REGISTRY -u "$REPO_HUB_U" --password-stdin
    - docker-compose logs
    - bash compare.sh
    - bash scan.sh
    - bash push.sh
build-job-1:
  tags:
    - debwithdock
  extends: .builder
  parallel:
    matrix:
      - VERSION: LATEST
        S6_VERSION: ["v2.2.0.1"]
