version: '3'
services:
  jitsi-web:
    image: ${BUILD_REGISTRY}/${PROJECT}/${CONTAINER_5}:${JITSI_VERSION}
    build: 
      context: ./web
      args:
        BUILD_REGISTRY_PRD: ${BUILD_REGISTRY_PRD}
        JITSI_DEB_VERSION: ${JITSI_DEB_VERSION}
        REGISTRY: ${REGISTRY}
        PROJECT: ${PROJECT}
        S6_VERSION: ${S6_VERSION}
    ports:
        - '${HTTP_PORT}:80'
    env_file:
        - ./.env_global
    networks:
        meet.jitsi:
            aliases:
                - meet.jitsi
  jitsi-prosody:
    image: ${BUILD_REGISTRY}/${PROJECT}/${CONTAINER_2}:${JITSI_VERSION}
    build: 
      context: ./prosody
      args: 
        JITSI_VERSION_GITHUB: ${JITSI_VERSION_GITHUB}
        REGISTRY: ${REGISTRY}
        PROJECT: ${PROJECT}
        BUILD_REGISTRY_PRD: ${BUILD_REGISTRY_PRD}
        S6_VERSION: ${S6_VERSION}
    env_file:
        - ./.env_global
    environment:
        - AUTHORIZED_USER
        - AUTHORIZED_USER_PASS
        - JICOFO_AUTH_PASSWORD
        - JICOFO_AUTH_USER
        - JVB_AUTH_PASSWORD
        - JVB_AUTH_USER
        - TURN_PASSWORD
    networks:
        meet.jitsi:
            aliases:
                - xmpp.meet.jitsi
  jitsi-jicofo:
    image: ${BUILD_REGISTRY}/${PROJECT}/${CONTAINER_4}:${JITSI_VERSION}
    build: 
      context: ./jicofo
      args:
        JICOFO_DEB_VERSION: ${JICOFO_DEB_VERSION}
        REGISTRY: ${REGISTRY}
    env_file:
        - ./.env_global
    environment:
        - JICOFO_AUTH_PASSWORD
        - JICOFO_AUTH_USER
    depends_on:
        - jitsi-prosody
    networks:
        meet.jitsi:
  jitsi-jvb:
    image: ${BUILD_REGISTRY}/${PROJECT}/${CONTAINER_3}:${JITSI_VERSION}
    build: 
      context: ./jvb
      args:
        JVB_DEB_VERSION: ${JVB_DEB_VERSION}
        REGISTRY: ${REGISTRY}
    ports:
        - '10000:10000/udp'
    env_file:
        - ./.env_global
    environment:
        - JVB_AUTH_USER
        - JVB_AUTH_PASSWORD
    depends_on:
        - jitsi-prosody
    networks:
        meet.jitsi:
            aliases:
                - jvb.meet.jitsi
  jitsi-turn:
    image: ${BUILD_REGISTRY}/${PROJECT}/${CONTAINER_6}:${COTURN_VERSION}
    build: 
      context: ./coturn
    volumes:
        - /data/data1/dockervols/jitsi/coturn/certs:/etc/coturn/certs
    ports:
        - '3478:3478/udp'
        - '5349:5349'
    env_file:
        - ./.env_global
    environment:
        - TURN_PASSWORD
    depends_on:
        - jitsi-prosody
        - jitsi-jvb
    networks:
        meet.jitsi:
            aliases:
                - meet.jitsi
networks:
    meet.jitsi:
