#!/bin/bash
INTERFACE=/usr/share/jitsi-meet/interface_config.js
if [ -z $DISABLE_JOIN_LEAVE_NOTIFICATIONS ]; then
  DISABLE_JOIN_LEAVE_NOTIFICATIONS=false
fi
if [ -z $DISABLE_FOCUS_INDICATOR ]; then
  DISABLE_FOCUS_INDICATOR=false
fi

sed -i "/^\s*DISABLE_JOIN_LEAVE_NOTIFICATIONS:/ s~:.*~: $DISABLE_JOIN_LEAVE_NOTIFICATIONS,~" $INTERFACE
sed -i "/^\s*DISABLE_FOCUS_INDICATOR:/ s~:.*~: $DISABLE_FOCUS_INDICATOR,~" $INTERFACE
